@ProductCatalogService_HostAddress = http://localhost:5009
@MockSkuId = aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
@OtherMockSkuId = bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb

GET {{ProductCatalogService_HostAddress}}/v1/products/{{MockSkuId}}/logistics
Accept: application/json

###

GET {{ProductCatalogService_HostAddress}}/v1/products/logistics/batch?skuIds={{MockSkuId}}&skuIds={{OtherMockSkuId}}
Accept: application/json
